name: Slides  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /slides get lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-g.zip slides/get/index.js node_modules
      - name: slide get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-g
            zip_file: m-s-slides-g.zip
      - name: /slides post lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-po.zip slides/post/index.js node_modules
      - name: slide get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-po
            zip_file: m-s-slides-po.zip
      - name: /slides/{slide_id} get lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-g.zip slides/slide_id/get/index.js node_modules
      - name: slide get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-g
            zip_file: m-s-slides-slide-g.zip
      - name: /slides/{slide_id} put lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-pu.zip slides/slide_id/put/index.js node_modules
      - name: slide get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-pu
            zip_file: m-s-slides-slide-pu.zip
      - name: /slides/{slide_id} delete lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-d.zip slides/slide_id/delete/index.js node_modules
      - name: slide get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-d
            zip_file: m-s-slides-slide-d.zip          
      - name: /slides/{slide_id}/tags get lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-tags-g.zip slides/slide_id/tags/get/index.js node_modules
      - name: slides get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-tags-g
            zip_file: m-s-slides-slide-tags-g.zip
      - name: /slides/{slide_id}/tags post lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-tags-po.zip slides/slide_id/tags/post/index.js node_modules
      - name: slides get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-tags-po
            zip_file: m-s-slides-slide-tags-po.zip
      - name: /slides/{slide_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/slides@main
        with:
            args: zip -qq -r m-s-slides-slide-tags-tag-d.zip slides/slide_id/tags/tag_id/delete/index.js node_modules
      - name: slides get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-slides-slide-tags-tag-d
            zip_file: m-s-slides-slide-tags-tag-d.zip            